# TOML configuration file for `jobrunner`.
#
# This file provides an organizational structure
# for bash files spread all over the repository
#
# `jobrunner` should be called from the root of
# a project directory to execute commands in a desired working directory. 
#
# All `job.toml` files present in a directory tree 
# are combined to a single dictionary during `setup` 
# or `submit` commands

# List of files that need to be included when
# setting up a job
config.setup = ["environment.sh"]

# List of files that need to be included when
# submitting a job
config.submit = ["environment.sh"]
