# TOML configuration file for `jobrunner`.

# Job schedular command for deploying
# simulations
job.schedular = "sbatch"

# Job input file name. All job.input in 
# directory tree will be combined to form this
# file
job.input = "flash.par"

# List of files that need to be included when
# setting up a job
config.setup = ["flash.sh"]
