# TOML configuration file for `jobrunner`.

# Job schedular command for deploying
# simulations
job.schedular = "sbatch"

# Job input file name. All job.input in
# directory tree will be combined to form this
# file
job.input = "flash.par"

# Schedular configuration resources requirement
# job name etc
config.schedular = [
    "#SBATCH --ntasks=5",
    "#SBATCH -t 0-30:00",
    "#SBATCH --job-name=pool_boiling",
]

# List of files that need to be included when
# setting up a job
config.setup = ["build.sh"]

# List of files to be included
# in submit script
config.submit = ["pool_boiling_heater.sh"]
